### ISSUE TITLE
Inquiry About OccRWKV Paper Release

### ISSUE THREAD

**Issue by Yaziwel** [jmwang0117/OccRWKV#1]
Hi, I’m gathering papers for [Awesome-RWKV-in-Vision](https://github.com/Yaziwel/Awesome-RWKV-in-Vision). I really appreciate the work on OccRWKV—when do you plan to release your paper on it?

**Comment by jmwang0117** [comment]
Thank you for your attention to our work. I will upload our paper to arXiv in a week.
