### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by GTrui6** [jmwang0117/OccRWKV#2]
Hi, thanks for your wonderful work. When i tried to run the "run_train.sh", it says “no module named 'networks.dsc'”. So i tried to use "pip install networks", and i tried many other versions of the package 'networks'. But it didnt work. And i also tried to find the local folder 'networks', but still didn't  find the 'dsc'. How can i sovle this?

**Comment by jmwang0117** [comment]
Hello,

Which file does this error come from? The code has not been cleaned up yet!

The dsc module should be removed from the code or replaced with networks.occrwkv

**Comment by GTrui6** [comment]
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    from utils.model import get_model
  File "/media/wanghai/NewSSD/Rui/OccRWKV/utils/model.py", line 1, in <module>
    from networks.dsc import DSC
ModuleNotFoundError: No module named 'networks.dsc'

It's in the "model.py", i suppose

**Comment by jmwang0117** [comment]
Please try to modify it this way. I will take the time to organize the code later. Thank you!

![image](https://github.com/user-attachments/assets/2b9f6861-1f8c-4fdb-8193-545dcb4df67e)
