### ISSUE TITLE
About wkv_op.cpp and wkv_cuda.cu

### ISSUE THREAD

**Issue by UserX0916** [jmwang0117/OccRWKV#3]
Hi, thanks for your wonderful work.I noticed that in line 117 of the file 'vrwkv.py' located in the directory 'OccRWKV\OccRWKV-main\networks', there is a line of code: `wkv_cuda = load(name="wkv", sources=["/home/jmwang/OccRWKV/networks/cuda/wkv_op.cpp", "/home/jmwang/OccRWKV/networks/cuda/wkv_cuda.cu"], verbose=True, extra_cuda_cflags=['-res-usage', '--maxrregcount 60', '--use_fast_math', '-O3', '-Xptxas -O3', f'-DTmax={T_MAX}'])`. However, I am unable to locate these two files. Could you please guide me on how to obtain them? Thank you so much!

**Comment by jmwang0117** [comment]
Hi, I updated the code, now you can find these two files, thanks!
